import 'dotenv/config';
import { drizzle } from 'drizzle-orm/node-postgres';
import { Pool } from 'pg';
import { users, books } from '../src/server/db/schema';
import { eq } from 'drizzle-orm';
import bcrypt from 'bcryptjs';

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

const db = drizzle(pool);

const DEMO_USER = {
  email: 'demo@quillify.com',
  password: 'demo123',
  confirmPassword: 'demo123',
  name: 'Demo User',
};

const DEMO_BOOKS = [
  // Adventure
  {
    title: 'Treasure Island',
    author: 'Robert Louis Stevenson',
    numberOfPages: 292,
    genre: 'Adventure',
    publishYear: 1883,
    isRead: true,
  },
  {
    title: 'The Call of the Wild',
    author: 'Jack London',
    numberOfPages: 232,
    genre: 'Adventure',
    publishYear: 1903,
    isRead: true,
  },
  {
    title: 'Robinson Crusoe',
    author: 'Daniel Defoe',
    numberOfPages: 320,
    genre: 'Adventure',
    publishYear: 1719,
    isRead: false,
  },
  {
    title: 'The Count of Monte Cristo',
    author: 'Alexandre Dumas',
    numberOfPages: 1276,
    genre: 'Adventure',
    publishYear: 1844,
    isRead: true,
  },
  {
    title: 'Journey to the Center of the Earth',
    author: 'Jules Verne',
    numberOfPages: 256,
    genre: 'Adventure',
    publishYear: 1864,
    isRead: false,
  },
  {
    title: "King Solomon's Mines",
    author: 'H. Rider Haggard',
    numberOfPages: 320,
    genre: 'Adventure',
    publishYear: 1885,
    isRead: false,
  },
  {
    title: 'The Three Musketeers',
    author: 'Alexandre Dumas',
    numberOfPages: 700,
    genre: 'Adventure',
    publishYear: 1844,
    isRead: true,
  },

  // Art
  {
    title: 'The Story of Art',
    author: 'E.H. Gombrich',
    numberOfPages: 688,
    genre: 'Art',
    publishYear: 1950,
    isRead: true,
  },
  {
    title: 'Ways of Seeing',
    author: 'John Berger',
    numberOfPages: 176,
    genre: 'Art',
    publishYear: 1972,
    isRead: true,
  },
  {
    title: 'The Lives of the Artists',
    author: 'Giorgio Vasari',
    numberOfPages: 592,
    genre: 'Art',
    publishYear: 1550,
    isRead: false,
  },
  {
    title: 'Concerning the Spiritual in Art',
    author: 'Wassily Kandinsky',
    numberOfPages: 80,
    genre: 'Art',
    publishYear: 1912,
    isRead: true,
  },
  {
    title: 'Art as Experience',
    author: 'John Dewey',
    numberOfPages: 371,
    genre: 'Art',
    publishYear: 1934,
    isRead: false,
  },

  // Biography
  {
    title: 'Steve Jobs',
    author: 'Walter Isaacson',
    numberOfPages: 656,
    genre: 'Biography',
    publishYear: 2011,
    isRead: true,
  },
  {
    title: 'The Autobiography of Malcolm X',
    author: 'Malcolm X & Alex Haley',
    numberOfPages: 500,
    genre: 'Biography',
    publishYear: 1965,
    isRead: true,
  },
  {
    title: 'Long Walk to Freedom',
    author: 'Nelson Mandela',
    numberOfPages: 656,
    genre: 'Biography',
    publishYear: 1994,
    isRead: true,
  },
  {
    title: 'Einstein: His Life and Universe',
    author: 'Walter Isaacson',
    numberOfPages: 704,
    genre: 'Biography',
    publishYear: 2007,
    isRead: false,
  },
  {
    title: 'Alexander Hamilton',
    author: 'Ron Chernow',
    numberOfPages: 818,
    genre: 'Biography',
    publishYear: 2004,
    isRead: true,
  },
  {
    title: 'Leonardo da Vinci',
    author: 'Walter Isaacson',
    numberOfPages: 624,
    genre: 'Biography',
    publishYear: 2017,
    isRead: false,
  },
  {
    title: 'Frida: A Biography of Frida Kahlo',
    author: 'Hayden Herrera',
    numberOfPages: 528,
    genre: 'Biography',
    publishYear: 1983,
    isRead: true,
  },

  // Business
  {
    title: 'Good to Great',
    author: 'Jim Collins',
    numberOfPages: 320,
    genre: 'Business',
    publishYear: 2001,
    isRead: true,
  },
  {
    title: 'The Lean Startup',
    author: 'Eric Ries',
    numberOfPages: 336,
    genre: 'Business',
    publishYear: 2011,
    isRead: true,
  },
  {
    title: 'Zero to One',
    author: 'Peter Thiel',
    numberOfPages: 224,
    genre: 'Business',
    publishYear: 2014,
    isRead: true,
  },
  {
    title: 'Think and Grow Rich',
    author: 'Napoleon Hill',
    numberOfPages: 238,
    genre: 'Business',
    publishYear: 1937,
    isRead: false,
  },
  {
    title: 'The 7 Habits of Highly Effective People',
    author: 'Stephen Covey',
    numberOfPages: 381,
    genre: 'Business',
    publishYear: 1989,
    isRead: true,
  },
  {
    title: 'Start with Why',
    author: 'Simon Sinek',
    numberOfPages: 256,
    genre: 'Business',
    publishYear: 2009,
    isRead: false,
  },
  {
    title: 'The Hard Thing About Hard Things',
    author: 'Ben Horowitz',
    numberOfPages: 304,
    genre: 'Business',
    publishYear: 2014,
    isRead: true,
  },

  // Children's
  {
    title: "Charlotte's Web",
    author: 'E.B. White',
    numberOfPages: 184,
    genre: "Children's",
    publishYear: 1952,
    isRead: true,
  },
  {
    title: 'Where the Wild Things Are',
    author: 'Maurice Sendak',
    numberOfPages: 48,
    genre: "Children's",
    publishYear: 1963,
    isRead: true,
  },
  {
    title: 'The Very Hungry Caterpillar',
    author: 'Eric Carle',
    numberOfPages: 26,
    genre: "Children's",
    publishYear: 1969,
    isRead: true,
  },
  {
    title: 'Goodnight Moon',
    author: 'Margaret Wise Brown',
    numberOfPages: 32,
    genre: "Children's",
    publishYear: 1947,
    isRead: true,
  },
  {
    title: 'The Cat in the Hat',
    author: 'Dr. Seuss',
    numberOfPages: 61,
    genre: "Children's",
    publishYear: 1957,
    isRead: true,
  },
  {
    title: 'Matilda',
    author: 'Roald Dahl',
    numberOfPages: 240,
    genre: "Children's",
    publishYear: 1988,
    isRead: true,
  },

  // Classics
  {
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    numberOfPages: 432,
    genre: 'Classics',
    publishYear: 1813,
    isRead: true,
  },
  {
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    numberOfPages: 336,
    genre: 'Classics',
    publishYear: 1960,
    isRead: true,
  },
  {
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    numberOfPages: 532,
    genre: 'Classics',
    publishYear: 1847,
    isRead: true,
  },
  {
    title: 'Wuthering Heights',
    author: 'Emily Brontë',
    numberOfPages: 416,
    genre: 'Classics',
    publishYear: 1847,
    isRead: false,
  },
  {
    title: 'Great Expectations',
    author: 'Charles Dickens',
    numberOfPages: 544,
    genre: 'Classics',
    publishYear: 1861,
    isRead: true,
  },
  {
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    numberOfPages: 180,
    genre: 'Classics',
    publishYear: 1925,
    isRead: true,
  },
  {
    title: 'Moby-Dick',
    author: 'Herman Melville',
    numberOfPages: 720,
    genre: 'Classics',
    publishYear: 1851,
    isRead: false,
  },

  // Cooking/Food
  {
    title: 'Mastering the Art of French Cooking',
    author: 'Julia Child',
    numberOfPages: 752,
    genre: 'Cooking/Food',
    publishYear: 1961,
    isRead: true,
  },
  {
    title: 'Salt, Fat, Acid, Heat',
    author: 'Samin Nosrat',
    numberOfPages: 480,
    genre: 'Cooking/Food',
    publishYear: 2017,
    isRead: true,
  },
  {
    title: 'The Joy of Cooking',
    author: 'Irma S. Rombauer',
    numberOfPages: 1200,
    genre: 'Cooking/Food',
    publishYear: 1931,
    isRead: false,
  },
  {
    title: 'Kitchen Confidential',
    author: 'Anthony Bourdain',
    numberOfPages: 312,
    genre: 'Cooking/Food',
    publishYear: 2000,
    isRead: true,
  },
  {
    title: 'The Food Lab',
    author: 'J. Kenji López-Alt',
    numberOfPages: 958,
    genre: 'Cooking/Food',
    publishYear: 2015,
    isRead: false,
  },
  {
    title: 'Plenty',
    author: 'Yotam Ottolenghi',
    numberOfPages: 288,
    genre: 'Cooking/Food',
    publishYear: 2010,
    isRead: true,
  },

  // Crime
  {
    title: 'The Godfather',
    author: 'Mario Puzo',
    numberOfPages: 448,
    genre: 'Crime',
    publishYear: 1969,
    isRead: true,
  },
  {
    title: 'The Silence of the Lambs',
    author: 'Thomas Harris',
    numberOfPages: 352,
    genre: 'Crime',
    publishYear: 1988,
    isRead: true,
  },
  {
    title: 'In Cold Blood',
    author: 'Truman Capote',
    numberOfPages: 343,
    genre: 'Crime',
    publishYear: 1966,
    isRead: true,
  },
  {
    title: 'The Girl with the Dragon Tattoo',
    author: 'Stieg Larsson',
    numberOfPages: 465,
    genre: 'Crime',
    publishYear: 2005,
    isRead: false,
  },
  {
    title: 'Big Little Lies',
    author: 'Liane Moriarty',
    numberOfPages: 460,
    genre: 'Crime',
    publishYear: 2014,
    isRead: true,
  },
  {
    title: 'Gone Girl',
    author: 'Gillian Flynn',
    numberOfPages: 419,
    genre: 'Crime',
    publishYear: 2012,
    isRead: true,
  },

  // Drama
  {
    title: 'Death of a Salesman',
    author: 'Arthur Miller',
    numberOfPages: 139,
    genre: 'Drama',
    publishYear: 1949,
    isRead: true,
  },
  {
    title: 'A Streetcar Named Desire',
    author: 'Tennessee Williams',
    numberOfPages: 142,
    genre: 'Drama',
    publishYear: 1947,
    isRead: true,
  },
  {
    title: 'Hamlet',
    author: 'William Shakespeare',
    numberOfPages: 342,
    genre: 'Drama',
    publishYear: 1603,
    isRead: true,
  },
  {
    title: 'Waiting for Godot',
    author: 'Samuel Beckett',
    numberOfPages: 109,
    genre: 'Drama',
    publishYear: 1952,
    isRead: false,
  },
  {
    title: 'The Crucible',
    author: 'Arthur Miller',
    numberOfPages: 152,
    genre: 'Drama',
    publishYear: 1953,
    isRead: true,
  },
  {
    title: "A Doll's House",
    author: 'Henrik Ibsen',
    numberOfPages: 104,
    genre: 'Drama',
    publishYear: 1879,
    isRead: false,
  },

  // Dystopian
  {
    title: '1984',
    author: 'George Orwell',
    numberOfPages: 328,
    genre: 'Dystopian',
    publishYear: 1949,
    isRead: true,
  },
  {
    title: 'Brave New World',
    author: 'Aldous Huxley',
    numberOfPages: 268,
    genre: 'Dystopian',
    publishYear: 1932,
    isRead: true,
  },
  {
    title: "The Handmaid's Tale",
    author: 'Margaret Atwood',
    numberOfPages: 311,
    genre: 'Dystopian',
    publishYear: 1985,
    isRead: true,
  },
  {
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    numberOfPages: 249,
    genre: 'Dystopian',
    publishYear: 1953,
    isRead: true,
  },
  {
    title: 'The Road',
    author: 'Cormac McCarthy',
    numberOfPages: 287,
    genre: 'Dystopian',
    publishYear: 2006,
    isRead: false,
  },
  {
    title: 'Station Eleven',
    author: 'Emily St. John Mandel',
    numberOfPages: 336,
    genre: 'Dystopian',
    publishYear: 2014,
    isRead: true,
  },

  // Essays
  {
    title: 'Self-Reliance and Other Essays',
    author: 'Ralph Waldo Emerson',
    numberOfPages: 96,
    genre: 'Essays',
    publishYear: 1841,
    isRead: true,
  },
  {
    title: 'Notes of a Native Son',
    author: 'James Baldwin',
    numberOfPages: 176,
    genre: 'Essays',
    publishYear: 1955,
    isRead: true,
  },
  {
    title: "A Room of One's Own",
    author: 'Virginia Woolf',
    numberOfPages: 112,
    genre: 'Essays',
    publishYear: 1929,
    isRead: true,
  },
  {
    title: 'Consider the Lobster',
    author: 'David Foster Wallace',
    numberOfPages: 343,
    genre: 'Essays',
    publishYear: 2005,
    isRead: false,
  },
  {
    title: 'Bad Feminist',
    author: 'Roxane Gay',
    numberOfPages: 336,
    genre: 'Essays',
    publishYear: 2014,
    isRead: true,
  },

  // Fantasy
  {
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    numberOfPages: 310,
    genre: 'Fantasy',
    publishYear: 1937,
    isRead: true,
  },
  {
    title: 'The Fellowship of the Ring',
    author: 'J.R.R. Tolkien',
    numberOfPages: 423,
    genre: 'Fantasy',
    publishYear: 1954,
    isRead: true,
  },
  {
    title: 'A Game of Thrones',
    author: 'George R.R. Martin',
    numberOfPages: 694,
    genre: 'Fantasy',
    publishYear: 1996,
    isRead: true,
  },
  {
    title: 'The Name of the Wind',
    author: 'Patrick Rothfuss',
    numberOfPages: 662,
    genre: 'Fantasy',
    publishYear: 2007,
    isRead: true,
  },
  {
    title: "Harry Potter and the Sorcerer's Stone",
    author: 'J.K. Rowling',
    numberOfPages: 309,
    genre: 'Fantasy',
    publishYear: 1997,
    isRead: true,
  },
  {
    title: 'The Way of Kings',
    author: 'Brandon Sanderson',
    numberOfPages: 1007,
    genre: 'Fantasy',
    publishYear: 2010,
    isRead: false,
  },
  {
    title: 'The Lion, the Witch and the Wardrobe',
    author: 'C.S. Lewis',
    numberOfPages: 206,
    genre: 'Fantasy',
    publishYear: 1950,
    isRead: true,
  },
  {
    title: 'American Gods',
    author: 'Neil Gaiman',
    numberOfPages: 541,
    genre: 'Fantasy',
    publishYear: 2001,
    isRead: true,
  },

  // Fiction
  {
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    numberOfPages: 277,
    genre: 'Fiction',
    publishYear: 1951,
    isRead: true,
  },
  {
    title: 'One Hundred Years of Solitude',
    author: 'Gabriel García Márquez',
    numberOfPages: 417,
    genre: 'Fiction',
    publishYear: 1967,
    isRead: true,
  },
  {
    title: 'The Kite Runner',
    author: 'Khaled Hosseini',
    numberOfPages: 371,
    genre: 'Fiction',
    publishYear: 2003,
    isRead: true,
  },
  {
    title: 'Life of Pi',
    author: 'Yann Martel',
    numberOfPages: 319,
    genre: 'Fiction',
    publishYear: 2001,
    isRead: false,
  },
  {
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    numberOfPages: 208,
    genre: 'Fiction',
    publishYear: 1988,
    isRead: true,
  },
  {
    title: 'A Man Called Ove',
    author: 'Fredrik Backman',
    numberOfPages: 337,
    genre: 'Fiction',
    publishYear: 2012,
    isRead: true,
  },

  // Gothic
  {
    title: 'Dracula',
    author: 'Bram Stoker',
    numberOfPages: 418,
    genre: 'Gothic',
    publishYear: 1897,
    isRead: true,
  },
  {
    title: 'Frankenstein',
    author: 'Mary Shelley',
    numberOfPages: 280,
    genre: 'Gothic',
    publishYear: 1818,
    isRead: true,
  },
  {
    title: 'The Picture of Dorian Gray',
    author: 'Oscar Wilde',
    numberOfPages: 254,
    genre: 'Gothic',
    publishYear: 1890,
    isRead: true,
  },
  {
    title: 'Rebecca',
    author: 'Daphne du Maurier',
    numberOfPages: 380,
    genre: 'Gothic',
    publishYear: 1938,
    isRead: false,
  },
  {
    title: 'The Strange Case of Dr Jekyll and Mr Hyde',
    author: 'Robert Louis Stevenson',
    numberOfPages: 144,
    genre: 'Gothic',
    publishYear: 1886,
    isRead: true,
  },
  {
    title: 'The Castle of Otranto',
    author: 'Horace Walpole',
    numberOfPages: 128,
    genre: 'Gothic',
    publishYear: 1764,
    isRead: false,
  },

  // Graphic Novel
  {
    title: 'Maus',
    author: 'Art Spiegelman',
    numberOfPages: 296,
    genre: 'Graphic Novel',
    publishYear: 1991,
    isRead: true,
  },
  {
    title: 'Watchmen',
    author: 'Alan Moore',
    numberOfPages: 416,
    genre: 'Graphic Novel',
    publishYear: 1987,
    isRead: true,
  },
  {
    title: 'Persepolis',
    author: 'Marjane Satrapi',
    numberOfPages: 160,
    genre: 'Graphic Novel',
    publishYear: 2000,
    isRead: true,
  },
  {
    title: 'Saga, Volume 1',
    author: 'Brian K. Vaughan',
    numberOfPages: 160,
    genre: 'Graphic Novel',
    publishYear: 2012,
    isRead: false,
  },
  {
    title: 'Fun Home',
    author: 'Alison Bechdel',
    numberOfPages: 232,
    genre: 'Graphic Novel',
    publishYear: 2006,
    isRead: true,
  },
  {
    title: 'Sandman Vol. 1: Preludes & Nocturnes',
    author: 'Neil Gaiman',
    numberOfPages: 240,
    genre: 'Graphic Novel',
    publishYear: 1989,
    isRead: true,
  },

  // Health & Wellness
  {
    title: 'Why We Sleep',
    author: 'Matthew Walker',
    numberOfPages: 368,
    genre: 'Health & Wellness',
    publishYear: 2017,
    isRead: true,
  },
  {
    title: 'The Body Keeps the Score',
    author: 'Bessel van der Kolk',
    numberOfPages: 464,
    genre: 'Health & Wellness',
    publishYear: 2014,
    isRead: true,
  },
  {
    title: 'How Not to Die',
    author: 'Michael Greger',
    numberOfPages: 576,
    genre: 'Health & Wellness',
    publishYear: 2015,
    isRead: false,
  },
  {
    title: 'Breath',
    author: 'James Nestor',
    numberOfPages: 304,
    genre: 'Health & Wellness',
    publishYear: 2020,
    isRead: true,
  },
  {
    title: 'The 4-Hour Body',
    author: 'Tim Ferriss',
    numberOfPages: 592,
    genre: 'Health & Wellness',
    publishYear: 2010,
    isRead: false,
  },

  // Historical Fiction
  {
    title: 'All the Light We Cannot See',
    author: 'Anthony Doerr',
    numberOfPages: 531,
    genre: 'Historical Fiction',
    publishYear: 2014,
    isRead: true,
  },
  {
    title: 'The Book Thief',
    author: 'Markus Zusak',
    numberOfPages: 552,
    genre: 'Historical Fiction',
    publishYear: 2005,
    isRead: true,
  },
  {
    title: 'The Nightingale',
    author: 'Kristin Hannah',
    numberOfPages: 440,
    genre: 'Historical Fiction',
    publishYear: 2015,
    isRead: false,
  },
  {
    title: 'Pachinko',
    author: 'Min Jin Lee',
    numberOfPages: 496,
    genre: 'Historical Fiction',
    publishYear: 2017,
    isRead: true,
  },
  {
    title: 'The Pillars of the Earth',
    author: 'Ken Follett',
    numberOfPages: 973,
    genre: 'Historical Fiction',
    publishYear: 1989,
    isRead: true,
  },
  {
    title: 'Wolf Hall',
    author: 'Hilary Mantel',
    numberOfPages: 604,
    genre: 'Historical Fiction',
    publishYear: 2009,
    isRead: false,
  },
  {
    title: 'The Name of the Rose',
    author: 'Umberto Eco',
    numberOfPages: 536,
    genre: 'Historical Fiction',
    publishYear: 1980,
    isRead: true,
  },

  // History
  {
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    numberOfPages: 443,
    genre: 'History',
    publishYear: 2011,
    isRead: true,
  },
  {
    title: 'Guns, Germs, and Steel',
    author: 'Jared Diamond',
    numberOfPages: 528,
    genre: 'History',
    publishYear: 1997,
    isRead: true,
  },
  {
    title: 'The Rise and Fall of the Third Reich',
    author: 'William L. Shirer',
    numberOfPages: 1280,
    genre: 'History',
    publishYear: 1960,
    isRead: false,
  },
  {
    title: "A People's History of the United States",
    author: 'Howard Zinn',
    numberOfPages: 729,
    genre: 'History',
    publishYear: 1980,
    isRead: true,
  },
  {
    title: 'The Silk Roads',
    author: 'Peter Frankopan',
    numberOfPages: 636,
    genre: 'History',
    publishYear: 2015,
    isRead: false,
  },
  {
    title: 'SPQR: A History of Ancient Rome',
    author: 'Mary Beard',
    numberOfPages: 608,
    genre: 'History',
    publishYear: 2015,
    isRead: true,
  },
  {
    title: 'The Wright Brothers',
    author: 'David McCullough',
    numberOfPages: 336,
    genre: 'History',
    publishYear: 2015,
    isRead: true,
  },

  // Horror
  {
    title: 'The Shining',
    author: 'Stephen King',
    numberOfPages: 447,
    genre: 'Horror',
    publishYear: 1977,
    isRead: true,
  },
  {
    title: 'It',
    author: 'Stephen King',
    numberOfPages: 1138,
    genre: 'Horror',
    publishYear: 1986,
    isRead: false,
  },
  {
    title: 'The Exorcist',
    author: 'William Peter Blatty',
    numberOfPages: 340,
    genre: 'Horror',
    publishYear: 1971,
    isRead: true,
  },
  {
    title: 'House of Leaves',
    author: 'Mark Z. Danielewski',
    numberOfPages: 709,
    genre: 'Horror',
    publishYear: 2000,
    isRead: false,
  },
  {
    title: 'Pet Sematary',
    author: 'Stephen King',
    numberOfPages: 374,
    genre: 'Horror',
    publishYear: 1983,
    isRead: true,
  },
  {
    title: 'The Haunting of Hill House',
    author: 'Shirley Jackson',
    numberOfPages: 246,
    genre: 'Horror',
    publishYear: 1959,
    isRead: true,
  },
  {
    title: 'Bird Box',
    author: 'Josh Malerman',
    numberOfPages: 262,
    genre: 'Horror',
    publishYear: 2014,
    isRead: false,
  },

  // Humor/Comedy
  {
    title: "The Hitchhiker's Guide to the Galaxy",
    author: 'Douglas Adams',
    numberOfPages: 224,
    genre: 'Humor/Comedy',
    publishYear: 1979,
    isRead: true,
  },
  {
    title: 'Good Omens',
    author: 'Terry Pratchett & Neil Gaiman',
    numberOfPages: 432,
    genre: 'Humor/Comedy',
    publishYear: 1990,
    isRead: true,
  },
  {
    title: 'Catch-22',
    author: 'Joseph Heller',
    numberOfPages: 453,
    genre: 'Humor/Comedy',
    publishYear: 1961,
    isRead: true,
  },
  {
    title: 'A Confederacy of Dunces',
    author: 'John Kennedy Toole',
    numberOfPages: 394,
    genre: 'Humor/Comedy',
    publishYear: 1980,
    isRead: false,
  },
  {
    title: 'Bossypants',
    author: 'Tina Fey',
    numberOfPages: 283,
    genre: 'Humor/Comedy',
    publishYear: 2011,
    isRead: true,
  },
  {
    title: 'Me Talk Pretty One Day',
    author: 'David Sedaris',
    numberOfPages: 288,
    genre: 'Humor/Comedy',
    publishYear: 2000,
    isRead: true,
  },

  // Literary Fiction
  {
    title: 'Beloved',
    author: 'Toni Morrison',
    numberOfPages: 324,
    genre: 'Literary Fiction',
    publishYear: 1987,
    isRead: true,
  },
  {
    title: 'The Road',
    author: 'Cormac McCarthy',
    numberOfPages: 287,
    genre: 'Literary Fiction',
    publishYear: 2006,
    isRead: true,
  },
  {
    title: 'Atonement',
    author: 'Ian McEwan',
    numberOfPages: 351,
    genre: 'Literary Fiction',
    publishYear: 2001,
    isRead: false,
  },
  {
    title: 'The Remains of the Day',
    author: 'Kazuo Ishiguro',
    numberOfPages: 245,
    genre: 'Literary Fiction',
    publishYear: 1989,
    isRead: true,
  },
  {
    title: 'Never Let Me Go',
    author: 'Kazuo Ishiguro',
    numberOfPages: 288,
    genre: 'Literary Fiction',
    publishYear: 2005,
    isRead: true,
  },
  {
    title: 'The Goldfinch',
    author: 'Donna Tartt',
    numberOfPages: 771,
    genre: 'Literary Fiction',
    publishYear: 2013,
    isRead: false,
  },
  {
    title: 'A Little Life',
    author: 'Hanya Yanagihara',
    numberOfPages: 720,
    genre: 'Literary Fiction',
    publishYear: 2015,
    isRead: true,
  },

  // Magical Realism
  {
    title: 'One Hundred Years of Solitude',
    author: 'Gabriel García Márquez',
    numberOfPages: 417,
    genre: 'Magical Realism',
    publishYear: 1967,
    isRead: true,
  },
  {
    title: 'The House of the Spirits',
    author: 'Isabel Allende',
    numberOfPages: 433,
    genre: 'Magical Realism',
    publishYear: 1982,
    isRead: false,
  },
  {
    title: 'Like Water for Chocolate',
    author: 'Laura Esquivel',
    numberOfPages: 256,
    genre: 'Magical Realism',
    publishYear: 1989,
    isRead: true,
  },
  {
    title: "Midnight's Children",
    author: 'Salman Rushdie',
    numberOfPages: 536,
    genre: 'Magical Realism',
    publishYear: 1981,
    isRead: false,
  },
  {
    title: 'The Wind-Up Bird Chronicle',
    author: 'Haruki Murakami',
    numberOfPages: 607,
    genre: 'Magical Realism',
    publishYear: 1994,
    isRead: true,
  },
  {
    title: 'Kafka on the Shore',
    author: 'Haruki Murakami',
    numberOfPages: 467,
    genre: 'Magical Realism',
    publishYear: 2002,
    isRead: true,
  },

  // Memoir
  {
    title: 'Educated',
    author: 'Tara Westover',
    numberOfPages: 334,
    genre: 'Memoir',
    publishYear: 2018,
    isRead: true,
  },
  {
    title: 'When Breath Becomes Air',
    author: 'Paul Kalanithi',
    numberOfPages: 256,
    genre: 'Memoir',
    publishYear: 2016,
    isRead: true,
  },
  {
    title: 'The Glass Castle',
    author: 'Jeannette Walls',
    numberOfPages: 288,
    genre: 'Memoir',
    publishYear: 2005,
    isRead: true,
  },
  {
    title: 'Born a Crime',
    author: 'Trevor Noah',
    numberOfPages: 304,
    genre: 'Memoir',
    publishYear: 2016,
    isRead: true,
  },
  {
    title: 'I Know Why the Caged Bird Sings',
    author: 'Maya Angelou',
    numberOfPages: 304,
    genre: 'Memoir',
    publishYear: 1969,
    isRead: false,
  },
  {
    title: "Angela's Ashes",
    author: 'Frank McCourt',
    numberOfPages: 368,
    genre: 'Memoir',
    publishYear: 1996,
    isRead: true,
  },
  {
    title: 'Wild',
    author: 'Cheryl Strayed',
    numberOfPages: 336,
    genre: 'Memoir',
    publishYear: 2012,
    isRead: false,
  },

  // Music
  {
    title: 'Just Kids',
    author: 'Patti Smith',
    numberOfPages: 304,
    genre: 'Music',
    publishYear: 2010,
    isRead: true,
  },
  {
    title: 'Life',
    author: 'Keith Richards',
    numberOfPages: 564,
    genre: 'Music',
    publishYear: 2010,
    isRead: false,
  },
  {
    title: 'Chronicles: Volume One',
    author: 'Bob Dylan',
    numberOfPages: 304,
    genre: 'Music',
    publishYear: 2004,
    isRead: true,
  },
  {
    title: 'Scar Tissue',
    author: 'Anthony Kiedis',
    numberOfPages: 480,
    genre: 'Music',
    publishYear: 2004,
    isRead: false,
  },
  {
    title: 'The Rest Is Noise',
    author: 'Alex Ross',
    numberOfPages: 640,
    genre: 'Music',
    publishYear: 2007,
    isRead: true,
  },

  // Mystery
  {
    title: 'And Then There Were None',
    author: 'Agatha Christie',
    numberOfPages: 272,
    genre: 'Mystery',
    publishYear: 1939,
    isRead: true,
  },
  {
    title: 'The Hound of the Baskervilles',
    author: 'Arthur Conan Doyle',
    numberOfPages: 256,
    genre: 'Mystery',
    publishYear: 1902,
    isRead: true,
  },
  {
    title: 'Murder on the Orient Express',
    author: 'Agatha Christie',
    numberOfPages: 256,
    genre: 'Mystery',
    publishYear: 1934,
    isRead: true,
  },
  {
    title: 'The Maltese Falcon',
    author: 'Dashiell Hammett',
    numberOfPages: 217,
    genre: 'Mystery',
    publishYear: 1930,
    isRead: false,
  },
  {
    title: 'The Big Sleep',
    author: 'Raymond Chandler',
    numberOfPages: 231,
    genre: 'Mystery',
    publishYear: 1939,
    isRead: true,
  },
  {
    title: 'In the Woods',
    author: 'Tana French',
    numberOfPages: 464,
    genre: 'Mystery',
    publishYear: 2007,
    isRead: true,
  },
  {
    title: "The No. 1 Ladies' Detective Agency",
    author: 'Alexander McCall Smith',
    numberOfPages: 235,
    genre: 'Mystery',
    publishYear: 1998,
    isRead: false,
  },

  // Non-Fiction
  {
    title: 'The Immortal Life of Henrietta Lacks',
    author: 'Rebecca Skloot',
    numberOfPages: 381,
    genre: 'Non-Fiction',
    publishYear: 2010,
    isRead: true,
  },
  {
    title: 'Freakonomics',
    author: 'Steven D. Levitt & Stephen J. Dubner',
    numberOfPages: 315,
    genre: 'Non-Fiction',
    publishYear: 2005,
    isRead: true,
  },
  {
    title: 'Outliers',
    author: 'Malcolm Gladwell',
    numberOfPages: 309,
    genre: 'Non-Fiction',
    publishYear: 2008,
    isRead: true,
  },
  {
    title: 'The Tipping Point',
    author: 'Malcolm Gladwell',
    numberOfPages: 301,
    genre: 'Non-Fiction',
    publishYear: 2000,
    isRead: false,
  },
  {
    title: 'Quiet',
    author: 'Susan Cain',
    numberOfPages: 352,
    genre: 'Non-Fiction',
    publishYear: 2012,
    isRead: true,
  },
  {
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    numberOfPages: 499,
    genre: 'Non-Fiction',
    publishYear: 2011,
    isRead: false,
  },

  // Parenting
  {
    title: 'How to Talk So Kids Will Listen',
    author: 'Adele Faber & Elaine Mazlish',
    numberOfPages: 286,
    genre: 'Parenting',
    publishYear: 1980,
    isRead: true,
  },
  {
    title: 'The Whole-Brain Child',
    author: 'Daniel J. Siegel',
    numberOfPages: 176,
    genre: 'Parenting',
    publishYear: 2011,
    isRead: true,
  },
  {
    title: 'Parenting with Love and Logic',
    author: 'Foster Cline & Jim Fay',
    numberOfPages: 256,
    genre: 'Parenting',
    publishYear: 1990,
    isRead: false,
  },
  {
    title: 'No-Drama Discipline',
    author: 'Daniel J. Siegel & Tina Payne Bryson',
    numberOfPages: 288,
    genre: 'Parenting',
    publishYear: 2014,
    isRead: true,
  },
  {
    title: 'Bringing Up Bébé',
    author: 'Pamela Druckerman',
    numberOfPages: 288,
    genre: 'Parenting',
    publishYear: 2012,
    isRead: false,
  },

  // Philosophy
  {
    title: 'Meditations',
    author: 'Marcus Aurelius',
    numberOfPages: 256,
    genre: 'Philosophy',
    publishYear: 2002,
    isRead: true,
  },
  {
    title: 'The Republic',
    author: 'Plato',
    numberOfPages: 416,
    genre: 'Philosophy',
    publishYear: 1992,
    isRead: false,
  },
  {
    title: 'Beyond Good and Evil',
    author: 'Friedrich Nietzsche',
    numberOfPages: 240,
    genre: 'Philosophy',
    publishYear: 1886,
    isRead: true,
  },
  {
    title: 'Being and Time',
    author: 'Martin Heidegger',
    numberOfPages: 589,
    genre: 'Philosophy',
    publishYear: 1927,
    isRead: false,
  },
  {
    title: 'The Stranger',
    author: 'Albert Camus',
    numberOfPages: 123,
    genre: 'Philosophy',
    publishYear: 1942,
    isRead: true,
  },
  {
    title: 'Thus Spoke Zarathustra',
    author: 'Friedrich Nietzsche',
    numberOfPages: 352,
    genre: 'Philosophy',
    publishYear: 1883,
    isRead: false,
  },
  {
    title: 'The Art of War',
    author: 'Sun Tzu',
    numberOfPages: 68,
    genre: 'Philosophy',
    publishYear: 1988,
    isRead: true,
  },

  // Poetry
  {
    title: 'The Waste Land and Other Poems',
    author: 'T.S. Eliot',
    numberOfPages: 88,
    genre: 'Poetry',
    publishYear: 1922,
    isRead: true,
  },
  {
    title: 'Leaves of Grass',
    author: 'Walt Whitman',
    numberOfPages: 448,
    genre: 'Poetry',
    publishYear: 1855,
    isRead: false,
  },
  {
    title: 'The Collected Poems of Emily Dickinson',
    author: 'Emily Dickinson',
    numberOfPages: 512,
    genre: 'Poetry',
    publishYear: 1890,
    isRead: true,
  },
  {
    title: 'Milk and Honey',
    author: 'Rupi Kaur',
    numberOfPages: 208,
    genre: 'Poetry',
    publishYear: 2014,
    isRead: true,
  },
  {
    title: 'The Odyssey',
    author: 'Homer',
    numberOfPages: 541,
    genre: 'Poetry',
    publishYear: 1996,
    isRead: false,
  },
  {
    title: 'Ariel',
    author: 'Sylvia Plath',
    numberOfPages: 96,
    genre: 'Poetry',
    publishYear: 1965,
    isRead: true,
  },

  // Politics
  {
    title: 'The Prince',
    author: 'Niccolò Machiavelli',
    numberOfPages: 140,
    genre: 'Politics',
    publishYear: 1532,
    isRead: true,
  },
  {
    title: 'The Communist Manifesto',
    author: 'Karl Marx & Friedrich Engels',
    numberOfPages: 96,
    genre: 'Politics',
    publishYear: 1848,
    isRead: true,
  },
  {
    title: 'On Liberty',
    author: 'John Stuart Mill',
    numberOfPages: 128,
    genre: 'Politics',
    publishYear: 1859,
    isRead: false,
  },
  {
    title: 'The Origins of Totalitarianism',
    author: 'Hannah Arendt',
    numberOfPages: 576,
    genre: 'Politics',
    publishYear: 1951,
    isRead: false,
  },
  {
    title: 'The Audacity of Hope',
    author: 'Barack Obama',
    numberOfPages: 375,
    genre: 'Politics',
    publishYear: 2006,
    isRead: true,
  },
  {
    title: 'Why Nations Fail',
    author: 'Daron Acemoglu & James A. Robinson',
    numberOfPages: 544,
    genre: 'Politics',
    publishYear: 2012,
    isRead: true,
  },

  // Programming
  {
    title: 'Clean Code',
    author: 'Robert C. Martin',
    numberOfPages: 464,
    genre: 'Programming',
    publishYear: 2008,
    isRead: true,
  },
  {
    title: 'The Pragmatic Programmer',
    author: 'David Thomas & Andrew Hunt',
    numberOfPages: 352,
    genre: 'Programming',
    publishYear: 1999,
    isRead: true,
  },
  {
    title: 'Design Patterns',
    author: 'Gang of Four',
    numberOfPages: 416,
    genre: 'Programming',
    publishYear: 1994,
    isRead: false,
  },
  {
    title: 'Code Complete',
    author: 'Steve McConnell',
    numberOfPages: 960,
    genre: 'Programming',
    publishYear: 1993,
    isRead: true,
  },
  {
    title: 'Structure and Interpretation of Computer Programs',
    author: 'Harold Abelson & Gerald Jay Sussman',
    numberOfPages: 657,
    genre: 'Programming',
    publishYear: 1985,
    isRead: false,
  },
  {
    title: "You Don't Know JS",
    author: 'Kyle Simpson',
    numberOfPages: 278,
    genre: 'Programming',
    publishYear: 2014,
    isRead: true,
  },

  // Psychology
  {
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    numberOfPages: 499,
    genre: 'Psychology',
    publishYear: 2011,
    isRead: true,
  },
  {
    title: "Man's Search for Meaning",
    author: 'Viktor E. Frankl',
    numberOfPages: 184,
    genre: 'Psychology',
    publishYear: 1946,
    isRead: true,
  },
  {
    title: 'The Interpretation of Dreams',
    author: 'Sigmund Freud',
    numberOfPages: 630,
    genre: 'Psychology',
    publishYear: 1899,
    isRead: false,
  },
  {
    title: 'Flow',
    author: 'Mihaly Csikszentmihalyi',
    numberOfPages: 303,
    genre: 'Psychology',
    publishYear: 1990,
    isRead: true,
  },
  {
    title: 'Influence',
    author: 'Robert B. Cialdini',
    numberOfPages: 320,
    genre: 'Psychology',
    publishYear: 1984,
    isRead: true,
  },
  {
    title: 'The Power of Habit',
    author: 'Charles Duhigg',
    numberOfPages: 371,
    genre: 'Psychology',
    publishYear: 2012,
    isRead: false,
  },

  // Religion/Spirituality
  {
    title: 'The Power of Now',
    author: 'Eckhart Tolle',
    numberOfPages: 236,
    genre: 'Religion/Spirituality',
    publishYear: 1997,
    isRead: true,
  },
  {
    title: 'Siddhartha',
    author: 'Hermann Hesse',
    numberOfPages: 152,
    genre: 'Religion/Spirituality',
    publishYear: 1922,
    isRead: true,
  },
  {
    title: 'The Tao Te Ching',
    author: 'Lao Tzu',
    numberOfPages: 160,
    genre: 'Religion/Spirituality',
    publishYear: 1989,
    isRead: true,
  },
  {
    title: 'Mere Christianity',
    author: 'C.S. Lewis',
    numberOfPages: 227,
    genre: 'Religion/Spirituality',
    publishYear: 1952,
    isRead: false,
  },
  {
    title: 'The Bhagavad Gita',
    author: 'Vyasa',
    numberOfPages: 288,
    genre: 'Religion/Spirituality',
    publishYear: 1985,
    isRead: false,
  },
  {
    title: 'When Things Fall Apart',
    author: 'Pema Chödrön',
    numberOfPages: 176,
    genre: 'Religion/Spirituality',
    publishYear: 1997,
    isRead: true,
  },

  // Romance
  {
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    numberOfPages: 432,
    genre: 'Romance',
    publishYear: 1813,
    isRead: true,
  },
  {
    title: 'Outlander',
    author: 'Diana Gabaldon',
    numberOfPages: 850,
    genre: 'Romance',
    publishYear: 1991,
    isRead: false,
  },
  {
    title: 'The Notebook',
    author: 'Nicholas Sparks',
    numberOfPages: 214,
    genre: 'Romance',
    publishYear: 1996,
    isRead: true,
  },
  {
    title: 'Me Before You',
    author: 'Jojo Moyes',
    numberOfPages: 369,
    genre: 'Romance',
    publishYear: 2012,
    isRead: true,
  },
  {
    title: 'Beach Read',
    author: 'Emily Henry',
    numberOfPages: 361,
    genre: 'Romance',
    publishYear: 2020,
    isRead: false,
  },
  {
    title: 'The Hating Game',
    author: 'Sally Thorne',
    numberOfPages: 384,
    genre: 'Romance',
    publishYear: 2016,
    isRead: true,
  },

  // Science
  {
    title: 'A Brief History of Time',
    author: 'Stephen Hawking',
    numberOfPages: 256,
    genre: 'Science',
    publishYear: 1988,
    isRead: true,
  },
  {
    title: 'The Selfish Gene',
    author: 'Richard Dawkins',
    numberOfPages: 360,
    genre: 'Science',
    publishYear: 1976,
    isRead: true,
  },
  {
    title: 'Cosmos',
    author: 'Carl Sagan',
    numberOfPages: 396,
    genre: 'Science',
    publishYear: 1980,
    isRead: true,
  },
  {
    title: 'The Origin of Species',
    author: 'Charles Darwin',
    numberOfPages: 502,
    genre: 'Science',
    publishYear: 1859,
    isRead: false,
  },
  {
    title: 'Silent Spring',
    author: 'Rachel Carson',
    numberOfPages: 400,
    genre: 'Science',
    publishYear: 1962,
    isRead: true,
  },
  {
    title: 'The Gene',
    author: 'Siddhartha Mukherjee',
    numberOfPages: 608,
    genre: 'Science',
    publishYear: 2016,
    isRead: false,
  },
  {
    title: 'Astrophysics for People in a Hurry',
    author: 'Neil deGrasse Tyson',
    numberOfPages: 224,
    genre: 'Science',
    publishYear: 2017,
    isRead: true,
  },

  // Science Fiction
  {
    title: 'Dune',
    author: 'Frank Herbert',
    numberOfPages: 688,
    genre: 'Science Fiction',
    publishYear: 1965,
    isRead: true,
  },
  {
    title: 'Foundation',
    author: 'Isaac Asimov',
    numberOfPages: 244,
    genre: 'Science Fiction',
    publishYear: 1951,
    isRead: true,
  },
  {
    title: "Ender's Game",
    author: 'Orson Scott Card',
    numberOfPages: 324,
    genre: 'Science Fiction',
    publishYear: 1985,
    isRead: true,
  },
  {
    title: 'Neuromancer',
    author: 'William Gibson',
    numberOfPages: 271,
    genre: 'Science Fiction',
    publishYear: 1984,
    isRead: false,
  },
  {
    title: 'The Martian',
    author: 'Andy Weir',
    numberOfPages: 369,
    genre: 'Science Fiction',
    publishYear: 2011,
    isRead: true,
  },
  {
    title: 'Snow Crash',
    author: 'Neal Stephenson',
    numberOfPages: 480,
    genre: 'Science Fiction',
    publishYear: 1992,
    isRead: false,
  },
  {
    title: 'The Left Hand of Darkness',
    author: 'Ursula K. Le Guin',
    numberOfPages: 304,
    genre: 'Science Fiction',
    publishYear: 1969,
    isRead: true,
  },
  {
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    numberOfPages: 496,
    genre: 'Science Fiction',
    publishYear: 2021,
    isRead: true,
  },

  // Self-Help
  {
    title: 'Atomic Habits',
    author: 'James Clear',
    numberOfPages: 320,
    genre: 'Self-Help',
    publishYear: 2018,
    isRead: true,
  },
  {
    title: 'How to Win Friends and Influence People',
    author: 'Dale Carnegie',
    numberOfPages: 288,
    genre: 'Self-Help',
    publishYear: 1936,
    isRead: true,
  },
  {
    title: 'The Subtle Art of Not Giving a F*ck',
    author: 'Mark Manson',
    numberOfPages: 224,
    genre: 'Self-Help',
    publishYear: 2016,
    isRead: true,
  },
  {
    title: 'Deep Work',
    author: 'Cal Newport',
    numberOfPages: 296,
    genre: 'Self-Help',
    publishYear: 2016,
    isRead: false,
  },
  {
    title: 'The Four Agreements',
    author: 'Don Miguel Ruiz',
    numberOfPages: 160,
    genre: 'Self-Help',
    publishYear: 1997,
    isRead: true,
  },
  {
    title: 'Mindset',
    author: 'Carol S. Dweck',
    numberOfPages: 320,
    genre: 'Self-Help',
    publishYear: 2006,
    isRead: true,
  },

  // Sports
  {
    title: 'Open',
    author: 'Andre Agassi',
    numberOfPages: 400,
    genre: 'Sports',
    publishYear: 2009,
    isRead: true,
  },
  {
    title: 'The Boys in the Boat',
    author: 'Daniel James Brown',
    numberOfPages: 404,
    genre: 'Sports',
    publishYear: 2013,
    isRead: true,
  },
  {
    title: 'Moneyball',
    author: 'Michael Lewis',
    numberOfPages: 317,
    genre: 'Sports',
    publishYear: 2003,
    isRead: true,
  },
  {
    title: 'Shoe Dog',
    author: 'Phil Knight',
    numberOfPages: 400,
    genre: 'Sports',
    publishYear: 2016,
    isRead: false,
  },
  {
    title: 'Friday Night Lights',
    author: 'H.G. Bissinger',
    numberOfPages: 432,
    genre: 'Sports',
    publishYear: 1990,
    isRead: true,
  },
  {
    title: 'The Mamba Mentality',
    author: 'Kobe Bryant',
    numberOfPages: 208,
    genre: 'Sports',
    publishYear: 2018,
    isRead: false,
  },

  // Technology
  {
    title: 'The Innovators',
    author: 'Walter Isaacson',
    numberOfPages: 560,
    genre: 'Technology',
    publishYear: 2014,
    isRead: true,
  },
  {
    title: 'Hackers',
    author: 'Steven Levy',
    numberOfPages: 520,
    genre: 'Technology',
    publishYear: 1984,
    isRead: false,
  },
  {
    title: 'The Soul of a New Machine',
    author: 'Tracy Kidder',
    numberOfPages: 293,
    genre: 'Technology',
    publishYear: 1981,
    isRead: true,
  },
  {
    title: 'Superintelligence',
    author: 'Nick Bostrom',
    numberOfPages: 352,
    genre: 'Technology',
    publishYear: 2014,
    isRead: false,
  },
  {
    title: 'The Second Machine Age',
    author: 'Erik Brynjolfsson & Andrew McAfee',
    numberOfPages: 336,
    genre: 'Technology',
    publishYear: 2014,
    isRead: true,
  },

  // Thriller
  {
    title: 'The Da Vinci Code',
    author: 'Dan Brown',
    numberOfPages: 454,
    genre: 'Thriller',
    publishYear: 2003,
    isRead: true,
  },
  {
    title: 'The Girl on the Train',
    author: 'Paula Hawkins',
    numberOfPages: 336,
    genre: 'Thriller',
    publishYear: 2015,
    isRead: true,
  },
  {
    title: 'The Hunt for Red October',
    author: 'Tom Clancy',
    numberOfPages: 387,
    genre: 'Thriller',
    publishYear: 1984,
    isRead: false,
  },
  {
    title: 'The Bourne Identity',
    author: 'Robert Ludlum',
    numberOfPages: 523,
    genre: 'Thriller',
    publishYear: 1980,
    isRead: true,
  },
  {
    title: 'Before I Go to Sleep',
    author: 'S.J. Watson',
    numberOfPages: 359,
    genre: 'Thriller',
    publishYear: 2011,
    isRead: false,
  },
  {
    title: 'Sharp Objects',
    author: 'Gillian Flynn',
    numberOfPages: 254,
    genre: 'Thriller',
    publishYear: 2006,
    isRead: true,
  },

  // Travel
  {
    title: 'On the Road',
    author: 'Jack Kerouac',
    numberOfPages: 307,
    genre: 'Travel',
    publishYear: 1957,
    isRead: true,
  },
  {
    title: 'Into the Wild',
    author: 'Jon Krakauer',
    numberOfPages: 224,
    genre: 'Travel',
    publishYear: 1996,
    isRead: true,
  },
  {
    title: 'Eat, Pray, Love',
    author: 'Elizabeth Gilbert',
    numberOfPages: 352,
    genre: 'Travel',
    publishYear: 2006,
    isRead: false,
  },
  {
    title: 'A Walk in the Woods',
    author: 'Bill Bryson',
    numberOfPages: 397,
    genre: 'Travel',
    publishYear: 1998,
    isRead: true,
  },
  {
    title: 'In Patagonia',
    author: 'Bruce Chatwin',
    numberOfPages: 224,
    genre: 'Travel',
    publishYear: 1977,
    isRead: false,
  },
  {
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    numberOfPages: 208,
    genre: 'Travel',
    publishYear: 1988,
    isRead: true,
  },

  // True Crime
  {
    title: 'In Cold Blood',
    author: 'Truman Capote',
    numberOfPages: 343,
    genre: 'True Crime',
    publishYear: 1966,
    isRead: true,
  },
  {
    title: 'Helter Skelter',
    author: 'Vincent Bugliosi',
    numberOfPages: 689,
    genre: 'True Crime',
    publishYear: 1974,
    isRead: false,
  },
  {
    title: 'The Devil in the White City',
    author: 'Erik Larson',
    numberOfPages: 447,
    genre: 'True Crime',
    publishYear: 2003,
    isRead: true,
  },
  {
    title: "I'll Be Gone in the Dark",
    author: 'Michelle McNamara',
    numberOfPages: 352,
    genre: 'True Crime',
    publishYear: 2018,
    isRead: true,
  },
  {
    title: 'Mindhunter',
    author: 'John E. Douglas',
    numberOfPages: 384,
    genre: 'True Crime',
    publishYear: 1995,
    isRead: false,
  },
  {
    title: 'Zodiac',
    author: 'Robert Graysmith',
    numberOfPages: 336,
    genre: 'True Crime',
    publishYear: 1986,
    isRead: true,
  },

  // Western
  {
    title: 'Lonesome Dove',
    author: 'Larry McMurtry',
    numberOfPages: 945,
    genre: 'Western',
    publishYear: 1985,
    isRead: true,
  },
  {
    title: 'True Grit',
    author: 'Charles Portis',
    numberOfPages: 234,
    genre: 'Western',
    publishYear: 1968,
    isRead: true,
  },
  {
    title: 'Blood Meridian',
    author: 'Cormac McCarthy',
    numberOfPages: 351,
    genre: 'Western',
    publishYear: 1985,
    isRead: false,
  },
  {
    title: 'Shane',
    author: 'Jack Schaefer',
    numberOfPages: 214,
    genre: 'Western',
    publishYear: 1949,
    isRead: true,
  },
  {
    title: 'The Sisters Brothers',
    author: 'Patrick deWitt',
    numberOfPages: 328,
    genre: 'Western',
    publishYear: 2011,
    isRead: false,
  },
  {
    title: 'News of the World',
    author: 'Paulette Jiles',
    numberOfPages: 213,
    genre: 'Western',
    publishYear: 2016,
    isRead: true,
  },

  // Young Adult
  {
    title: 'The Hunger Games',
    author: 'Suzanne Collins',
    numberOfPages: 374,
    genre: 'Young Adult',
    publishYear: 2008,
    isRead: true,
  },
  {
    title: 'The Fault in Our Stars',
    author: 'John Green',
    numberOfPages: 313,
    genre: 'Young Adult',
    publishYear: 2012,
    isRead: true,
  },
  {
    title: 'Twilight',
    author: 'Stephenie Meyer',
    numberOfPages: 498,
    genre: 'Young Adult',
    publishYear: 2005,
    isRead: false,
  },
  {
    title: 'Divergent',
    author: 'Veronica Roth',
    numberOfPages: 487,
    genre: 'Young Adult',
    publishYear: 2011,
    isRead: true,
  },
  {
    title: 'The Perks of Being a Wallflower',
    author: 'Stephen Chbosky',
    numberOfPages: 213,
    genre: 'Young Adult',
    publishYear: 1999,
    isRead: true,
  },
  {
    title: 'The Maze Runner',
    author: 'James Dashner',
    numberOfPages: 384,
    genre: 'Young Adult',
    publishYear: 2009,
    isRead: false,
  },
  {
    title: 'The Giver',
    author: 'Lois Lowry',
    numberOfPages: 240,
    genre: 'Young Adult',
    publishYear: 1993,
    isRead: true,
  },
];

async function seed() {
  const forceReseed = process.argv.includes('--force');

  try {
    console.log('Seeding demo user and books...');

    // Check if demo user exists
    const [existingUser] = await db.select().from(users).where(eq(users.email, DEMO_USER.email));

    let demoUser: typeof existingUser;

    if (existingUser) {
      console.log('Demo user already exists!');
      demoUser = existingUser;

      // Ensure demo user has verified email
      if (!existingUser.emailVerifiedAt) {
        await db
          .update(users)
          .set({ emailVerifiedAt: new Date() })
          .where(eq(users.id, existingUser.id));
        console.log('Updated demo user with verified email');
      }
    } else {
      // Create demo user with verified email
      const hashedPassword = await bcrypt.hash(DEMO_USER.password, 12);
      const [newUser] = await db
        .insert(users)
        .values({
          email: DEMO_USER.email,
          password: hashedPassword,
          name: DEMO_USER.name,
          emailVerifiedAt: new Date(),
        })
        .returning();
      demoUser = newUser;
      console.log('Created demo user with verified email');
    }

    // Check if books already exist for this user
    const existingBooks = await db.select().from(books).where(eq(books.userId, demoUser!.id));

    if (existingBooks.length > 0 && !forceReseed) {
      console.log(`Demo user already has ${existingBooks.length} books. Skipping book creation.`);
      console.log('Run with --force to delete existing books and re-seed.');
    } else {
      if (existingBooks.length > 0 && forceReseed) {
        console.log(`Deleting ${existingBooks.length} existing books...`);
        await db.delete(books).where(eq(books.userId, demoUser!.id));
      }
      // Create books in batches for better performance
      const batchSize = 50;
      for (let i = 0; i < DEMO_BOOKS.length; i += batchSize) {
        const batch = DEMO_BOOKS.slice(i, i + batchSize);
        await db.insert(books).values(
          batch.map((book) => ({
            userId: demoUser!.id,
            ...book,
          }))
        );
        console.log(`Inserted books ${i + 1} to ${Math.min(i + batchSize, DEMO_BOOKS.length)}`);
      }
      console.log(`Created ${DEMO_BOOKS.length} books`);
    }

    // Count genres
    const genreCounts = DEMO_BOOKS.reduce(
      (acc, book) => {
        acc[book.genre] = (acc[book.genre] || 0) + 1;
        return acc;
      },
      {} as Record<string, number>
    );

    console.log('\nSeeding complete!');
    console.log(`\nDemo credentials:`);
    console.log(`   Email: ${DEMO_USER.email}`);
    console.log(`   Password: ${DEMO_USER.password}`);
    console.log(
      `   Books: ${DEMO_BOOKS.length} (${DEMO_BOOKS.filter((b) => b.isRead).length} read, ${DEMO_BOOKS.filter((b) => !b.isRead).length} unread)`
    );
    console.log(`\nGenre distribution:`);
    Object.entries(genreCounts)
      .sort((a, b) => b[1] - a[1])
      .forEach(([genre, count]) => {
        console.log(`   ${genre}: ${count}`);
      });
  } catch (error) {
    console.error('Error seeding database:', error);
    throw error;
  } finally {
    await pool.end();
  }
}

seed();
